# Generated by Django 2.2.13 on 2020-06-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200619_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagefub',
            new_name='image',
        ),
    ]
