# Generated by Django 2.2.13 on 2020-06-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200619_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
