# Generated by Django 2.2.13 on 2020-06-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200620_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='gsoc.jpeg', upload_to='images/'),
        ),
    ]
